export const mapColumnFn = {
  BYTEL: {
    mapColumnADM: (item: string[]) => {
      return {
        id: item?.[0],
        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],
        email: item?.[19],
        "e-mail": item?.[20],
        TEL2: item?.[13],
        Fournisseur_actuel: item?.[12],
        CP: item?.[26],
        Depuis: item?.[14],
        Options: item?.[16],
        Preference: item?.[17],
        time2call: "",
        Prix: item?.[37],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnVIPP: (item: string[]) => {
      return {
        id: item?.[0],
        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[16],
        "e-mail": item?.[32],
        TEL2: item?.[17],
        Fournisseur_actuel: item?.[13],
        CP: item?.[18],
        Depuis: item?.[38],
        Options: item?.[39],
        Preference: item?.[41],
        time2call: "",
        Prix: item?.[47],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnEUROCRM: (item: string[]) => {
      return {
        id: item?.[0],
        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[20],
        "e-mail": item?.[30],
        TEL2: item?.[19],
        Fournisseur_actuel: item?.[12],
        CP: item?.[34],
        Depuis: item?.[27],
        Options: item?.[33],
        Preference: item?.[36],
        time2call: "",
        Prix: item?.[43],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnAFFINICIA: (item: string[]) => {
      return {
        id: item?.[0],
        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],
        email: item?.[14],
        "e-mail": item?.[15],
        TEL2: item?.[12],
        Fournisseur_actuel: item?.[20],
        CP: item?.[13],
        Depuis: item?.[23],
        Options: item?.[22],
        Preference: item?.[21],
        time2call: "",
        Prix: item?.[32],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnATLAS: (item: string[]) => {
      return {
        id: item?.[0],
        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[12],
        "e-mail": item?.[13],
        TEL2: item?.[14],
        Fournisseur_actuel: item?.[15],
        CP: item?.[16],
        Depuis: item?.[17],
        Options: item?.[18],
        Preference: item?.[19],
        time2call: "",
        Prix: item?.[21],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnFEDALA: (item: string[]) => {
      return {
        id: item?.[0],
        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[12],
        "e-mail": item?.[13],
        TEL2: item?.[14],
        Fournisseur_actuel: item?.[15],
        CP: item?.[16],
        Depuis: item?.[17],
        Options: item?.[18],
        Preference: item?.[19],
        time2call: "",
        Prix: item?.[21],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnMARINA: (item: string[]) => {
      return {
        id: item?.[0],
        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[12],
        "e-mail": item?.[13],
        TEL2: item?.[14],
        Fournisseur_actuel: item?.[15],
        CP: item?.[16],
        Depuis: item?.[17],
        Options: item?.[18],
        Preference: item?.[19],
        time2call: "",
        Prix: item?.[21],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnRIGHTPLACE: (item: string[]) => {
      return {
        id: item?.[0],
        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[17],
        "e-mail": item?.[18],
        TEL2: item?.[16],
        Fournisseur_actuel: item?.[12],
        CP: item?.[15],
        Depuis: item?.[13],
        Options: item?.[14],
        Preference: item?.[22],
        time2call: "",
        Prix: item?.[29],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnWEBHELP: (item: string[]) => {
      return {
        id: item?.[0],
        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[21],
        "e-mail": item?.[23],
        TEL2: item?.[20],
        Fournisseur_actuel: item?.[17],
        CP: item?.[26],
        Depuis: item?.[18],
        Options: item?.[25],
        Preference: item?.[28],
        time2call: "",
        Prix: item?.[34],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnALGER: (item: string[]) => {
      return {
        id: item?.[0],
        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[14],
        "e-mail": item?.[15],
        TEL2: item?.[13],
        Fournisseur_actuel: item?.[12],
        CP: item?.[18],
        Depuis: item?.[16],
        Options: item?.[19],
        Preference: item?.[20],
        time2call: "",
        Prix: item?.[28],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },
  },

  ORANGE: {
    mapColumnARMATIS: (item: string[]) => {
      return {
        id: item?.[0],
        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[12],
        "e-mail": item?.[13],
        TEL2: item?.[14],
        Fournisseur_actuel: item?.[15],
        CP: item?.[16],
        Depuis: item?.[17],
        Options: item?.[18],
        Preference: item?.[22],
        time2call: "",
        Prix: item?.[25],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnTUNIS: (item: string[]) => {
      return {
        id: item?.[0],
        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[12],
        "e-mail": item?.[13],
        TEL2: item?.[14],
        Fournisseur_actuel: item?.[15],
        CP: item?.[16],
        Depuis: item?.[17],
        Options: item?.[18],
        Preference: item?.[19],
        time2call: "",
        Prix: item?.[21],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnDPI: (item: string[]) => {
      return {
        id: item?.[0],
        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[12],
        "e-mail": item?.[13],
        TEL2: item?.[14],
        Fournisseur_actuel: item?.[15],
        CP: item?.[16],
        Depuis: item?.[17],
        Options: item?.[18],
        Preference: item?.[19],
        time2call: "",
        Prix: item?.[21],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnKONECTA: (item: string[]) => {
      return {
        id: item?.[0],
        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[22],
        "e-mail": item?.[23],
        TEL2: item?.[24],
        Fournisseur_actuel: item?.[13],
        CP: item?.[21],
        Depuis: item?.[37],
        Options: item?.[39],
        Preference: item?.[44],
        time2call: "",
        Prix: item?.[46],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnSATEL: (item: string[]) => {
      return {
        id: item?.[0],
        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[15],
        "e-mail": item?.[15],
        TEL2: item?.[16],
        Fournisseur_actuel: item?.[12],
        CP: item?.[34],
        Depuis: item?.[27],
        Options: item?.[20],
        Preference: item?.[22],
        time2call: "",
        Prix: item?.[33],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnTERSEA: (item: string[]) => {
      return {
        id: item?.[0],
        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[12],
        "e-mail": item?.[13],
        TEL2: item?.[14],
        Fournisseur_actuel: item?.[15],
        CP: item?.[16],
        Depuis: item?.[17],
        Options: item?.[18],
        Preference: item?.[19],
        time2call: "",
        Prix: item?.[21],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },
  },

  ENERGIE: {},
};
