import { generateNumericId } from "./id-generator";

export const mapColumnFn = {
  BYTEL: {
    mapColumnMASTER_BYTEL: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[12],
        "e-mail": item?.[13],
        TEL2: item?.[14],
        Fournisseur_actuel: item?.[15],
        CP: item?.[16],
        Depuis: item?.[17],
        Options: item?.[18],
        Preference: item?.[19],
        time2call: item?.[20],
        Prix: item?.[21],
        Recherche: item?.[22],
        nom: item?.[23],
        prenom: item?.[24],
        Ville: item?.[25],
        utm_device: item?.[26],
        lead_device: item?.[27],
        operateur_mobile: item?.[33],
        is_internal: "true",
      };
    },

    mapColumnADM_DAKAR: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[12],
        "e-mail": item?.[13],
        TEL2: item?.[14],
        Fournisseur_actuel: item?.[15],
        CP: item?.[16],
        Depuis: item?.[17],
        Options: item?.[18],
        Preference: item?.[19],
        time2call: item?.[20],
        Prix: item?.[21],
        Recherche: item?.[22],
        nom: item?.[23],
        prenom: item?.[24],
        Ville: item?.[25],
        utm_device: item?.[26],
        lead_device: item?.[27],
        operateur_mobile: item?.[28],
        is_internal: "true",
      };
    },

    mapColumnADM: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[19],
        "e-mail": item?.[20],
        TEL2: item?.[13],
        Fournisseur_actuel: item?.[25],
        CP: item?.[26],
        Depuis: item?.[14],
        Options: item?.[16],
        Preference: item?.[17],
        time2call: "",
        Prix: item?.[37],
        Recherche: item?.[41],
        nom: item?.[39],
        prenom: item?.[40],
        Ville: "",
        utm_device: item?.[42],
        lead_device: item?.[43],
        operateur_mobile: item?.[38],
        is_internal: "true",
      };
    },

    mapColumnEUROCRM: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[20],
        "e-mail": item?.[30],
        TEL2: item?.[19],
        Fournisseur_actuel: item?.[12],
        CP: item?.[34],
        Depuis: item?.[27],
        Options: item?.[33],
        Preference: item?.[36],
        time2call: "",
        Prix: item?.[43],
        Recherche: item?.[44],
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: item?.[45],
        lead_device: "",
        operateur_mobile: item?.[53],
        is_internal: "true",
      };
    },

    mapColumnATLAS: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[12],
        "e-mail": item?.[13],
        TEL2: item?.[14],
        Fournisseur_actuel: item?.[15],
        CP: item?.[16],
        Depuis: item?.[17],
        Options: item?.[18],
        Preference: item?.[19],
        time2call: item?.[20],
        Prix: item?.[21],
        Recherche: item?.[22],
        nom: item?.[23],
        prenom: item?.[24],
        Ville: item?.[25],
        utm_device: item?.[26],
        lead_device: item?.[27],
        operateur_mobile: item?.[28],
        is_internal: "true",
      };
    },

    mapColumnFEDALA: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[12],
        "e-mail": item?.[13],
        TEL2: item?.[14],
        Fournisseur_actuel: item?.[15],
        CP: item?.[16],
        Depuis: item?.[17],
        Options: item?.[18],
        Preference: item?.[19],
        time2call: item?.[20],
        Prix: item?.[21],
        Recherche: item?.[22],
        nom: item?.[23],
        prenom: item?.[24],
        Ville: item?.[25],
        utm_device: item?.[26],
        lead_device: item?.[27],
        operateur_mobile: item?.[28],
        is_internal: "true",
      };
    },

    mapColumnMARINA: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[12],
        "e-mail": item?.[13],
        TEL2: item?.[14],
        Fournisseur_actuel: item?.[15],
        CP: item?.[16],
        Depuis: item?.[17],
        Options: item?.[18],
        Preference: item?.[19],
        time2call: item?.[20],
        Prix: item?.[21],
        Recherche: item?.[22],
        nom: item?.[23],
        prenom: item?.[24],
        Ville: item?.[25],
        utm_device: item?.[26],
        lead_device: item?.[27],
        operateur_mobile: item?.[28],
        is_internal: "true",
      };
    },

    mapColumnVIPP: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[16],
        "e-mail": item?.[32],
        TEL2: item?.[17],
        Fournisseur_actuel: item?.[13],
        CP: item?.[18],
        Depuis: item?.[38],
        Options: item?.[39],
        Preference: item?.[41],
        time2call: "",
        Prix: item?.[47],
        Recherche: "",
        nom: item?.[55],
        prenom: item?.[56],
        Ville: "",
        utm_device: item?.[52],
        lead_device: "",
        operateur_mobile: item?.[51],
        is_internal: "true",
      };
    },

    mapColumnWEBHELP: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[21],
        "e-mail": item?.[23],
        TEL2: item?.[20],
        Fournisseur_actuel: item?.[17],
        CP: item?.[26],
        Depuis: item?.[18],
        Options: item?.[25],
        Preference: item?.[28],
        time2call: "",
        Prix: item?.[34],
        Recherche: item?.[43],
        nom: item?.[41],
        prenom: item?.[42],
        Ville: "",
        utm_device: item?.[43],
        lead_device: "",
        operateur_mobile: item?.[37],
        is_internal: "true",
      };
    },

    mapColumnALGER: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[14],
        "e-mail": item?.[15],
        TEL2: item?.[13],
        Fournisseur_actuel: item?.[12],
        CP: item?.[18],
        Depuis: item?.[16],
        Options: item?.[19],
        Preference: item?.[20],
        time2call: "",
        Prix: item?.[28],
        Recherche: item?.[31],
        nom: item?.[32],
        prenom: item?.[33],
        Ville: "",
        utm_device: item?.[35],
        lead_device: item?.[34],
        operateur_mobile: item?.[29],
        is_internal: "true",
      };
    },
  },

  ORANGE: {
    mapColumnARMATIS: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[12],
        "e-mail": item?.[13],
        TEL2: item?.[14],
        Fournisseur_actuel: item?.[15],
        CP: item?.[16],
        Depuis: item?.[17],
        Options: item?.[18],
        Preference: item?.[22],
        time2call: "",
        Prix: item?.[25],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnTUNIS: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[12],
        "e-mail": item?.[13],
        TEL2: item?.[14],
        Fournisseur_actuel: item?.[15],
        CP: item?.[16],
        Depuis: item?.[17],
        Options: item?.[18],
        Preference: item?.[19],
        time2call: "",
        Prix: item?.[21],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnDPI: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[12],
        "e-mail": item?.[13],
        TEL2: item?.[14],
        Fournisseur_actuel: item?.[15],
        CP: item?.[16],
        Depuis: item?.[17],
        Options: item?.[18],
        Preference: item?.[19],
        time2call: "",
        Prix: item?.[21],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnKONECTA: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[22],
        "e-mail": item?.[23],
        TEL2: item?.[24],
        Fournisseur_actuel: item?.[13],
        CP: item?.[21],
        Depuis: item?.[37],
        Options: item?.[39],
        Preference: item?.[44],
        time2call: "",
        Prix: item?.[46],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnSATEL: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[15],
        "e-mail": item?.[15],
        TEL2: item?.[16],
        Fournisseur_actuel: item?.[12],
        CP: item?.[34],
        Depuis: item?.[27],
        Options: item?.[20],
        Preference: item?.[22],
        time2call: "",
        Prix: item?.[33],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnTERSEA: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[12],
        "e-mail": item?.[13],
        TEL2: item?.[14],
        Fournisseur_actuel: item?.[15],
        CP: item?.[16],
        Depuis: item?.[17],
        Options: item?.[18],
        Preference: item?.[19],
        time2call: "",
        Prix: item?.[21],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },
  },

  SFR: {
    /* DISCONTINUED */
    mapColumnAFFINICIA: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],
        email: item?.[14],
        "e-mail": item?.[15],
        TEL2: item?.[12],
        Fournisseur_actuel: item?.[20],
        CP: item?.[13],
        Depuis: item?.[23],
        Options: item?.[22],
        Preference: item?.[21],
        time2call: "",
        Prix: item?.[32],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },
    /* DISCONTINUED */

    mapColumnK_SFR: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[17],
        "e-mail": item?.[18],
        TEL2: item?.[16],
        Fournisseur_actuel: item?.[12],
        CP: item?.[15],
        Depuis: item?.[13],
        Options: item?.[14],
        Preference: item?.[22],
        time2call: "",
        Prix: item?.[29],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnRIGHTPLACE: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[17],
        "e-mail": item?.[18],
        TEL2: item?.[16],
        Fournisseur_actuel: item?.[12],
        CP: item?.[15],
        Depuis: item?.[13],
        Options: item?.[14],
        Preference: item?.[22],
        time2call: "",
        Prix: item?.[29],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnW_AGADIR: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[17],
        "e-mail": item?.[18],
        TEL2: item?.[16],
        Fournisseur_actuel: item?.[12],
        CP: item?.[15],
        Depuis: item?.[13],
        Options: item?.[14],
        Preference: item?.[22],
        time2call: "",
        Prix: item?.[29],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnW_DAKAR: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[17],
        "e-mail": item?.[18],
        TEL2: item?.[16],
        Fournisseur_actuel: item?.[12],
        CP: item?.[15],
        Depuis: item?.[13],
        Options: item?.[14],
        Preference: item?.[22],
        time2call: "",
        Prix: item?.[29],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnW_FES: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[17],
        "e-mail": item?.[18],
        TEL2: item?.[16],
        Fournisseur_actuel: item?.[12],
        CP: item?.[15],
        Depuis: item?.[13],
        Options: item?.[14],
        Preference: item?.[22],
        time2call: "",
        Prix: item?.[29],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },

    mapColumnW_MARRAKECH: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        email: item?.[17],
        "e-mail": item?.[18],
        TEL2: item?.[16],
        Fournisseur_actuel: item?.[12],
        CP: item?.[15],
        Depuis: item?.[13],
        Options: item?.[14],
        Preference: item?.[22],
        time2call: "",
        Prix: item?.[29],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },
  },

  FREE: {
    mapColumnPURPREMIUM: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],
        email: item?.[14],
        "e-mail": item?.[15],
        TEL2: item?.[12],
        Fournisseur_actuel: item?.[20],
        CP: item?.[13],
        Depuis: item?.[23],
        Options: item?.[22],
        Preference: item?.[21],
        time2call: "",
        Prix: item?.[32],
        Recherche: "",
        nom: "",
        prenom: "",
        Ville: "",
        utm_device: "",
        lead_device: "",
        operateur_mobile: "",
        is_internal: "true",
      };
    },
  },

  ENERGIE: {
    mapColumnADMTOTAL: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        Offre: item?.[12],
        Chauffage: item?.[13],
        Fournisseur: item?.[14],
        montant: item?.[15],
        CP: item?.[16],
        Nom: item?.[17],
        Prenom: item?.[18],
        TEL2: item?.[19],
        Email: item?.[20],
        Ville: item?.[21],
        Adresse: item?.[22],
        street_address: item?.[23],
        city: item?.[24],
        Projet: item?.[25],
        Preference: item?.[26],
        is_internal: "true",
      };
    },

    mapColumnADMVATTENFALL: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        Offre: item?.[12],
        Chauffage: item?.[13],
        Fournisseur: item?.[14],
        montant: item?.[15],
        CP: item?.[16],
        Nom: item?.[17],
        Prenom: item?.[18],
        TEL2: item?.[19],
        Email: item?.[20],
        Ville: item?.[21],
        Adresse: item?.[22],
        street_address: item?.[23],
        city: item?.[24],
        Projet: item?.[25],
        Preference: item?.[36],
        is_internal: "true",
      };
    },

    mapColumnAFFINICIATOTAL: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        Offre: item?.[12],
        Chauffage: item?.[13],
        Fournisseur: item?.[14],
        montant: item?.[15],
        CP: item?.[16],
        Nom: item?.[17],
        Prenom: item?.[18],
        TEL2: item?.[19],
        Email: item?.[20],
        Ville: item?.[21],
        Adresse: item?.[22],
        street_address: item?.[23],
        city: item?.[24],
        Projet: item?.[33],
        Preference: item?.[38],
        is_internal: "true",
      };
    },

    mapColumnENGIE: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        Offre: item?.[12],
        Chauffage: item?.[13],
        Fournisseur: item?.[14],
        montant: item?.[15],
        CP: item?.[16],
        Nom: item?.[17],
        Prenom: item?.[18],
        TEL2: item?.[19],
        Email: item?.[20],
        Ville: item?.[21],
        Adresse: item?.[22],
        street_address: item?.[23],
        city: item?.[24],
        Projet: item?.[32],
        Preference: item?.[36],
        is_internal: "true",
      };
    },

    mapColumnWEKIWI: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        Offre: item?.[12],
        Chauffage: item?.[13],
        Fournisseur: item?.[14],
        montant: item?.[15],
        CP: item?.[16],
        Nom: item?.[17],
        Prenom: item?.[18],
        TEL2: item?.[19],
        Email: item?.[20],
        Ville: item?.[21],
        Adresse: item?.[22],
        street_address: item?.[23],
        city: item?.[24],
        Projet: item?.[25],
        Preference: item?.[36],
        is_internal: "true",
      };
    },

    mapColumnENI: (item: string[]) => {
      return {
        id: generateNumericId(),

        created_time: item?.[1],
        ad_id: item?.[2],
        ad_name: item?.[3],
        adset_id: item?.[4],
        adset_name: item?.[5],
        campaign_id: item?.[6],
        campaign_name: item?.[7],
        form_id: item?.[8],
        form_name: item?.[9],
        is_organic: item?.[10],
        platform: item?.[11],

        Offre: item?.[12],
        Chauffage: item?.[13],
        Fournisseur: item?.[14],
        montant: item?.[15],
        CP: item?.[16],
        Nom: item?.[17],
        Prenom: item?.[18],
        TEL2: item?.[19],
        Email: item?.[20],
        Ville: item?.[21],
        Adresse: item?.[22],
        street_address: item?.[23],
        city: item?.[24],
        Projet: item?.[33],
        Preference: item?.[34],
        is_internal: "true",
      };
    },
  },
};
