export const mapColumnADM = (item: string[]) => {
  return {
    id: item?.[0],
    created_time: item?.[1],
    ad_id: item?.[2],
    ad_name: item?.[3],
    adset_id: item?.[4],
    adset_name: item?.[5],
    campaign_id: item?.[6],
    campaign_name: item?.[7],
    form_id: item?.[8],
    form_name: item?.[9],
    is_organic: item?.[10],
    platform: item?.[11],
    email: item?.[19],
    "e-mail": item?.[20],
    TEL2: item?.[13],
    Fournisseur_actuel: item?.[12],
    CP: item?.[26],
    Depuis: item?.[14],
    Options: item?.[16],
    Preference: item?.[17],
    time2call: "",
    Prix: "", // TO DO: Change this with Price
    Recherche: "",
    nom: "",
    prenom: "",
    Ville: "",
    utm_device: "",
    lead_device: "",
    operateur_mobile: "",
    is_internal: "true",
  };
};

export const mapColumnVIPP = (item: string[]) => {
  return {
    id: item?.[0],
    created_time: item?.[1],
    ad_id: item?.[2],
    ad_name: item?.[3],
    adset_id: item?.[4],
    adset_name: item?.[5],
    campaign_id: item?.[6],
    campaign_name: item?.[7],
    form_id: item?.[8],
    form_name: item?.[9],
    is_organic: item?.[10],
    platform: item?.[11],

    email: item?.[16],
    "e-mail": item?.[32],
    TEL2: item?.[17],
    Fournisseur_actuel: item?.[13],
    CP: item?.[18],
    Depuis: item?.[38],
    Options: item?.[39],
    Preference: item?.[41],
    time2call: "",
    Prix: item?.[47],
    Recherche: "",
    nom: "",
    prenom: "",
    Ville: "",
    utm_device: "",
    lead_device: "",
    operateur_mobile: "",
    is_internal: "true",
  };
};

export const mapColumnEUROCRM = (item: string[]) => {
  return {
    id: item?.[0],
    created_time: item?.[1],
    ad_id: item?.[2],
    ad_name: item?.[3],
    adset_id: item?.[4],
    adset_name: item?.[5],
    campaign_id: item?.[6],
    campaign_name: item?.[7],
    form_id: item?.[8],
    form_name: item?.[9],
    is_organic: item?.[10],
    platform: item?.[11],

    email: item?.[20],
    "e-mail": item?.[30],
    TEL2: item?.[19],
    Fournisseur_actuel: item?.[12],
    CP: item?.[34],
    Depuis: item?.[27],
    Options: item?.[33],
    Preference: item?.[36],
    time2call: "",
    Prix: item?.[43],
    Recherche: "",
    nom: "",
    prenom: "",
    Ville: "",
    utm_device: "",
    lead_device: "",
    operateur_mobile: "",
    is_internal: "true",
  };
};

export const mapColumnWEBHELP = (item: string[]) => {
  return {
    id: item[1],
    created_time: item[2],
    ad_id: item[3],
    ad_name: item[4],
    adset_id: item[6],
    adset_name: item[6],
    campaign_id: item[7],
    campaign_name: item[8],
    form_id: item[9],
    form_name: item[10],
    is_organic: item[11],
    platform: item[12],
    TEL2: item[21],
    CP: item[27],
    email: item[24],
    "e-mail": item[22],
    Fournisseur_actuel: item[18],
    preferences: item[29],
    options: item[26],
    Depuis: item[19],
  };
};

export const mapColumnKONECTA = (item: string[]) => {
  return {
    id: item[1],
    created_time: item[2],
    ad_id: item[3],
    ad_name: item[4],
    adset_id: item[6],
    adset_name: item[6],
    campaign_id: item[7],
    campaign_name: item[8],
    form_id: item[9],
    form_name: item[10],
    is_organic: item[11],
    platform: item[12],
    TEL2: item[25],
    CP: item[22],
    email: item[23],
    "e-mail": item[24],
    Fournisseur_actuel: item[14],
    preferences: item[45],
    options: item[40],
    Depuis: item[38],
  };
};

export const mapColumnWEBHELPALGER = (item: string[]) => {
  return {
    id: item[1],
    created_time: item[2],
    ad_id: item[3],
    ad_name: item[4],
    adset_id: item[6],
    adset_name: item[6],
    campaign_id: item[7],
    campaign_name: item[8],
    form_id: item[9],
    form_name: item[10],
    is_organic: item[11],
    platform: item[12],
    TEL2: item[14],
    CP: item[20],
    email: item[15],
    "e-mail": item[16],
    Fournisseur_actuel: item[13],
    preferences: item[21],
    options: item[20],
    Depuis: item[17],
  };
};

export const mapColumnAFFINICIA = (item: string[]) => {
  return {
    id: item?.[0],
    created_time: item?.[1],
    ad_id: item?.[2],
    ad_name: item?.[3],
    adset_id: item?.[4],
    adset_name: item?.[5],
    campaign_id: item?.[6],
    campaign_name: item?.[7],
    form_id: item?.[8],
    form_name: item?.[9],
    is_organic: item?.[10],
    platform: item?.[11],
    email: item?.[14],
    "e-mail": item?.[15],
    TEL2: item?.[12],
    Fournisseur_actuel: item?.[20],
    CP: item?.[13],
    Depuis: item?.[23],
    Options: item?.[22],
    Preference: item?.[21],
    time2call: "",
    Prix: item?.[32],
    Recherche: "",
    nom: "",
    prenom: "",
    Ville: "",
    utm_device: "",
    lead_device: "",
    operateur_mobile: "",
    is_internal: "true",
  };
};

export const mapColumnRIGHTPLACE = (item: string[]) => {
  return {
    id: item[1],
    created_time: item[2],
    ad_id: item[3],
    ad_name: item[4],
    adset_id: item[6],
    adset_name: item[6],
    campaign_id: item[7],
    campaign_name: item[8],
    form_id: item[9],
    form_name: item[10],
    is_organic: item[11],
    platform: item[12],
    TEL2: item[13],
    CP: item[17],
    email: item[18],
    "e-mail": item[19],
    Fournisseur_actuel: item[13],
    preferences: item[23],
    options: item[15],
    Depuis: item[14],
  };
};
